### ISSUE TITLE
Incorrectly responding to the ?hello cmd when invoked by invalid user

### ISSUE THREAD

**Issue by josh-green** [rougesheep/jhongbot#2]
## Issue Description

There seems to be a bug in the allow list filtering for who can invoke the `?hello` command. It was recently attempted by a malicious and invalid user and the Jhongbot incorrectly responded with the following:

> BOT Jhongbot: Hello @bad.user!

## Expected Behaviour

I would assume that a more appropriate response should be returned when invoked by a non-allowed user, for example:

> BOT Jhongbot: Eat a dick, @bad.user B=====D

Let me know if you'd like some help with this issue, thanks.

**Comment by rougesheep** [comment]
I'll look into it but pull requests are always appreciated
